### ISSUE TITLE
ImportProxies not working

### ISSUE THREAD

**Issue by ghost** [neerajwadhwa/apigeeselectivemigrationtool#1]
Hi Neeraj,

I am trying to migrate between organizations. I have configured the tool as per the instructions. The exportProxies works fine, all the proxies are exported from the organization. But when I try to run the importProxies command I am running on error. I am not sure what the issue would be.,

node:22844) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'revision' of undefined
    at C:\Users\ramaiahkothandaramai\apigee-selective-migration-tool\lib\commands\importProxies.js:326:58
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:22844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 187)

May be you could help me here.

Regards,
Aravind

**Comment by santvant** [comment]
Hi Aravand,

Are you able to export and import?

I am facing issue while exporting the proxies
